---
- name: Install remote facts
  hosts: labservers
  become: yes
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
  - name: Create remote directory
    file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}"
  - name: Install new facts
    copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
...
