---
- name: Install Appache and start the services
  hosts: labservers
  become: yes
  become_user: root
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python-httplib2
    rule: http
  tasks:
    - name: Install required packages
      yum:
        name: 
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          #- "{{ python_pkg }}"
        state: latest

    - name: "Start and enable the {{ firewall_service }} service"
      service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: Start and enable the "{{ web_service }}" service
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started
 
    - name: Create content to be served
      copy:
        content: "Example seb content"
        dest: /var/www/html/index.html
    
    - name: Open teh port for the {{ rule }}
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled
... 
          
